ADMIN_ROLE = "Admin"
MODERATOR_ROLE = "Moderator"
DEVELOPER_ROLE = "Developer"
HELPER_ROLE = "Helper"

SCRIPT_CREATE_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE]
SCRIPT_UPDATE_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE]
SCRIPT_STATUS_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE, MODERATOR_ROLE]
CHANGELOG_CREATE_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE]
FAQ_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE, MODERATOR_ROLE]
FEATURE_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE]
SCRIPT_STYLE_ROLES = [ADMIN_ROLE, DEVELOPER_ROLE]

STATUS_CHOICES = ["stable", "degraded", "broken", "updating", "discontinued"]
